name: Build Chrome Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v-0.0.1'
jobs:
  build-and-release:
    if: contains(github.event.head_commit.message, 'build')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install web-ext
        run: npm install -g web-ext

      # 开始打包
      - name: Build extension
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: web-ext build --source-dir . --artifacts-dir artifacts
      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v-0.0.1")
          # Increment the patch version
          current_version=${latest_tag#v-}  # Remove 'v-' prefix
          IFS='.' read -r major minor patch <<< "$current_version"
          new_version="v-$major.$minor.$((patch + 1))"
          echo "new_tag=$new_version" >> $GITHUB_OUTPUT
        shell: bash
      # 发布到 release
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ steps.get_latest_tag.outputs.new_tag }}
          name: Release ${{ steps.get_latest_tag.outputs.new_tag }}
          artifacts: artifacts/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          body: |
            ## What's Changed
            ${{ github.event.head_commit.message }}
            ## current version
            ${{ steps.get_latest_tag.outputs.new_tag }}
